# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ObjetsPref
                                 A QGIS plugin
 Objets préférés
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-11-27
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Gérôme PECHEUR (IGN)
        email                : gerome.pecheur@ign.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os

from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QDialog, QInputDialog, QMenu
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis._core import QgsProject

# Import the code for the dialog
from .objet_prefere_dialog import ObjetsPrefDialog

REP_CONFIG = "CONFIG"
FIC_OBJET_PREFERES = "objets_preferes.json"

class ObjetsPref:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.layer = None
        self.dlg = None
        self.iface = iface
        self._fic_objets_pref = None


    def initGui(self):
        pass

    def unload(self):
        pass

    def get_dossier_objets_pref(self) -> str:
        """
            Retourne le chemin du dossier des objets préférés.
            :return: str
            """
        return os.path.join(os.path.dirname(__file__),"OBJ_PREF")

    def set_fic_objetpreferes(self):
        self._fic_objets_pref = os.path.join(self.get_dossier_objets_pref(), FIC_OBJET_PREFERES)

    def get_fic_objetpreferes(self):
        return self._fic_objets_pref

    def get_objetspreferes(self):
        if self.get_fic_objetpreferes() is None:
            self.set_fic_objetpreferes()
        if os.path.exists(self.get_fic_objetpreferes()):
            with open(self.get_fic_objetpreferes(), "r") as f:
                return [line.strip() for line in f.readlines()]
        else:
            return []

    def on_ajouter_objet_prefere(self):
        project = QgsProject.instance()
        layers = project.mapLayers().values()
        list_layer = [layer.name() for layer in layers]
        valeur, ok = QInputDialog.getItem(
            None,
            "Sélection",
            "Choisir ... :",
            list_layer,
            0,
            False
        )
        if ok:
            self.dlg.listWidget.addItem(valeur)
            self.add_obj_pef_to_fic(valeur)


    def add_obj_pef_to_fic(self, objet_prefere):
        os.makedirs(self.get_dossier_objets_pref(), exist_ok=True)
        with open(self.get_fic_objetpreferes(), "a") as f:
            f.write(objet_prefere + "\n")

    def get_obj_pref_from_fic(self):
        if os.path.exists(self.get_fic_objetpreferes()):
            with open(self.get_fic_objetpreferes(), "r") as f:
                return [line.strip() for line in f.readlines()]
        else:
            return []

    def init_list_widget(self):
        objets_pref = self.get_obj_pref_from_fic()
        self.dlg.listWidget.clear()
        for obj in objets_pref:
            self.dlg.listWidget.addItem(obj)

    def context_menu(self,point):
        item = self.dlg.listWidget.itemAt(point)
        # Si clic en dehors d’une ligne → ne rien afficher
        if item is None:
            return
        menu = QMenu()
        action_supprimer = menu.addAction("Supprimer")
        action = menu.exec_(self.dlg.listWidget.mapToGlobal(point))

        if item:
            if action == action_supprimer:
                self.dlg.listWidget.takeItem(self.dlg.listWidget.row(item))
                # et on réécrit le fichier sans l'item supprimé
                objets_pref = self.get_obj_pref_from_fic()
                objets_pref = [obj for obj in objets_pref if obj != item.text()]
                with open(self.get_fic_objetpreferes(), "w") as f:
                    for obj in objets_pref:
                        f.write(obj + "\n")

    def on_clic_objet_prefere(self):

        item = self.dlg.listWidget.currentItem()
        if item:
            project = QgsProject.instance()
            self.layer = project.mapLayersByName(item.text())

            if self.layer:
                self.layer[0].featureAdded.connect(self.on_entite_cree)
                self.iface.setActiveLayer(self.layer[0])
                self.layer[0].startEditing()
                self.iface.actionAddFeature().trigger()

    def on_entite_cree(self):
        # apres une creation, on repasse en mode selection
        self.iface.actionSelect().trigger()

    def run(self):
        """Run method that performs all the real work"""
        if self.dlg is not None and self.dlg.isVisible():
            return
        self.dlg = ObjetsPrefDialog()
        self.dlg.setParent(self.iface.mainWindow())
        self.dlg.setWindowFlags(Qt.Dialog | Qt.WindowTitleHint | Qt.WindowCloseButtonHint)

        # slot pour le bouton "Ajouter un objet préféré"
        self.dlg.pushButtonAdd.clicked.connect(self.on_ajouter_objet_prefere)

        # self.layer.featureAdded.connect(self.on_entite_cree)

        # slot de listwidget
        self.dlg.listWidget.itemClicked.connect(self.on_clic_objet_prefere)
        # Connecter le menu contextuel
        self.dlg.listWidget.setContextMenuPolicy(3)  # Qt.CustomContextMenu
        self.dlg.listWidget.customContextMenuRequested.connect(self.context_menu)

        self.set_fic_objetpreferes()
        self.init_list_widget()

        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # # See if OK was pressed
        if result == QDialog.Rejected:
            pass

