# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ObjetsPref
                                 A QGIS plugin
 Objets préférés
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-11-27
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Gérôme PECHEUR (IGN)
        email                : gerome.pecheur@ign.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os
import webbrowser
import json

from qgis.PyQt.QtCore import QSize,QPoint
from qgis.PyQt.uic import loadUi
from qgis.PyQt.QtWidgets import QInputDialog, QMenu,QApplication
from qgis.core import QgsProject,QgsMapLayer,QgsApplication

from pathlib import Path

# Import the code for the dialog
from .objet_prefere_dialog import ObjetsPrefDialog
from .mapping_version import *

FIC_OBJET_PREFERES = "objets_preferes.json"
REP_OBJET_PREFERES = "OBJ_PREF"
TITRE = "Objets préférés"

class ObjetsPref():
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.layer = None
        self.dlg = None
        self.iface = iface
        self._fic_objets_pref = None


    def initGui(self):
        self.iface.projectRead.connect(self.on_project_opened)
        # événement fermeture de qgis
        QgsApplication.instance().aboutToQuit.connect(self.fermeture_qgis)

    def unload(self):
        pass

    def get_dossier_objets_pref(self) -> str:
        """
            Retourne le chemin du dossier des objets préférés.
            :return: str
            """
        # return os.path.join(os.path.dirname(__file__),"OBJ_PREF")
        projet = QgsProject.instance()
        chemin_projet = Path(projet.fileName())
        path_obj_pref = Path(chemin_projet.parent, REP_OBJET_PREFERES)
        return str(path_obj_pref)

    def set_fic_objetpreferes(self):
        self._fic_objets_pref = os.path.join(self.get_dossier_objets_pref(), FIC_OBJET_PREFERES)

    def get_fic_objetpreferes(self):
        return self._fic_objets_pref


    def on_apropos(self):
        self.dlgAProposDe = QDialog()
        loadUi(os.path.join(os.path.dirname(__file__), "aproposde.ui"), self.dlgAProposDe)
        self.dlgAProposDe.setWindowFlags(WindowStaysOnTopHint | WindowCloseButtonHint)
        self.dlgAProposDe.pushButtonAffichedoc.clicked.connect(self.afficheDoc)
        self.dlgAProposDe.exec()

    def afficheDoc(self):
        webbrowser.open("https://ignf.github.io/objets-preferes-qgis-plugin/")


    def on_ajouter_objet_prefere(self):
        project = QgsProject.instance()
        layers = project.mapLayers().values()
        # uniquement des layers vectorielles
        list_layer = [layer.name() for layer in layers if layer.type() == QgsMapLayer.VectorLayer]
        valeur, ok = QInputDialog.getItem(
            None,
            "Sélection",
            "Choisir ... :",
            list_layer,
            0,
            False
        )
        if ok:
            self.dlg.listWidget.addItem(valeur)
            self.add_obj_pref_to_fic(valeur)


    def sauve_to_json(self):
        objets_pref = []
        for i in range(self.dlg.listWidget.count()):
            objets_pref.append(self.dlg.listWidget.item(i).text())
        with open(self.get_fic_objetpreferes(), "w",encoding="utf-8") as f:
            json.dump(objets_pref, f, indent=2)


    def add_obj_pref_to_fic(self, objet_prefere):
        os.makedirs(self.get_dossier_objets_pref(), exist_ok=True)
        # 1. charger existant
        try:
            with open(self.get_fic_objetpreferes(), "r", encoding="utf-8") as f:
                objets = json.load(f)
        except Exception:
            objets = []
        # ajouter si pas déjà présent
        if objet_prefere not in objets:
            objets.append(objet_prefere)
        # réécrire fichier complet
        with open(self.get_fic_objetpreferes(), "w", encoding="utf-8") as f:
            json.dump(objets, f, indent=2, ensure_ascii=False)

    # retourne une liste de tous les objets préférés
    def get_obj_pref_from_fic(self):
        if os.path.exists(self.get_fic_objetpreferes()):
            try:
                with open(self.get_fic_objetpreferes(), "r", encoding="utf-8") as f:
                    return json.load(f)
            except json.JSONDecodeError:
                return []
        else:
            return []

    def init_list_widget(self):
        objets_pref = self.get_obj_pref_from_fic()
        self.dlg.listWidget.clear()
        for obj in objets_pref:
            self.dlg.listWidget.addItem(obj)

    def context_menu(self,point):
        item = self.dlg.listWidget.itemAt(point)
        # Si clic en dehors d’une ligne → ne rien afficher
        if item is None:
            return
        menu = QMenu()
        action_supprimer = menu.addAction("Supprimer")
        action = menu.exec(self.dlg.listWidget.mapToGlobal(point))

        if item:
            if action == action_supprimer:
                self.dlg.listWidget.takeItem(self.dlg.listWidget.row(item))
                objets_pref = self.get_obj_pref_from_fic()
                #  on redefini objets_pref sans l'item supprimé
                objets_pref = [obj for obj in objets_pref if obj != item.text()]
                with open(self.get_fic_objetpreferes(), "w",encoding="utf-8") as f:
                        # f.write(obj + "\n")
                        json.dump(objets_pref, f, indent=2)

    def on_suppr_objet_prefere(self):
        item = self.dlg.listWidget.currentItem()
        if item is None:
            return
        # suppression de l'item dans la listwidget
        self.dlg.listWidget.takeItem(self.dlg.listWidget.row(item))
        # et on réécrit le fichier sans l'item supprimé
        objets_pref = self.get_obj_pref_from_fic()
        objets_pref = [obj for obj in objets_pref if obj != item.text()]
        with open(self.get_fic_objetpreferes(), "w",encoding="utf-8") as f:
                # f.write(obj + "\n")
                json.dump(objets_pref, f, indent=2)

    def on_clic_objet_prefere(self):
        item = self.dlg.listWidget.currentItem()
        if item:
            project = QgsProject.instance()
            self.layer = project.mapLayersByName(item.text())
            if self.layer:
                self.iface.setActiveLayer(self.layer[0])

    def on_activer_saisie(self):
        if self.layer:
            self.layer[0].featureAdded.connect(self.on_entite_cree)
            self.layer[0].startEditing()
            self.iface.actionAddFeature().trigger()

    def on_entite_cree(self):
        # apres une creation, on repasse en mode selection
        self.iface.actionSelect().trigger()

    def sauve_position_dial(self):
        settings = QSettings(NativeFormat, UserScope,"IGN", TITRE)
        settings.setValue("position", self.dlg.pos())
        settings.setValue("taille", self.dlg.size())
        settings.setValue("visible", self.dlg.isVisible())


    def restore_position_dial(self):
        settings = QSettings(NativeFormat, UserScope, "IGN", TITRE)
        pos = settings.value("position", type=QPoint)
        size = settings.value("taille", type=QSize)
        if not pos:
            return
        screens = QApplication.screens()
        multi = len(screens) > 1
        # Vérifie si la position est sur un des écrans
        on_screen = any(screen.geometry().contains(pos) for screen in screens)
        if on_screen:
            self.dlg.move(pos)
            if size:
                self.dlg.resize(size)
        else:
            # Si un seul écran → replacer en haut-gauche
            if not multi:
                self.dlg.move(QPoint(0, 0))
            else:
                # Multi-écran mais position invalide → centrer sur écran principal
                primary = QApplication.primaryScreen().geometry()
                center = primary.center()
                self.dlg.move(center - self.dlg.rect().center())

    def on_project_opened(self):
        settings = QSettings(NativeFormat, UserScope, "IGN", TITRE)
        visible = settings.value("visible", False, type=bool)
        if visible:
            self.run()

    def on_dialog_closed(self):
        self.sauve_to_json()
        self.sauve_position_dial()
        self.dlg = None

    def fermeture_qgis(self):
        self.sauve_position_dial()


    def run(self):
        """Run method that performs all the real work"""
        if self.dlg is not None and self.dlg.isVisible():
            return
        self.dlg = ObjetsPrefDialog()
        self.dlg.setParent(self.iface.mainWindow())
        self.dlg.setWindowFlags(Dialog | WindowTitleHint | WindowCloseButtonHint)
        self.dlg.setWindowTitle(TITRE)

        self.dlg.listWidget.setDragDropMode(InternalMove)
        self.dlg.listWidget.setDefaultDropAction(MoveAction)
        self.dlg.listWidget.setDragEnabled(True)
        self.dlg.listWidget.setAcceptDrops(True)
        self.dlg.listWidget.setDropIndicatorShown(True)
        self.dlg.listWidget.setSelectionMode(SingleSelection)

        # connection de la fermeture du dialogue
        self.dlg.finished.connect(self.on_dialog_closed)

        self.restore_position_dial()

        # slot pour le bouton "Ajouter un objet préféré"
        self.dlg.pushButtonAdd.clicked.connect(self.on_ajouter_objet_prefere)
        self.dlg.pushButtonAdd.setToolTip("Ajouter un objet préféré")

        # slot pour le bouton "Supprimer un objet préféré"
        self.dlg.pushButtonSuppr.clicked.connect(self.on_suppr_objet_prefere)
        self.dlg.pushButtonSuppr.setToolTip("Supprimer un objet préféré")

        # slot pour le bouton "Activer la saisie"
        self.dlg.pushButton_activer_saisie.clicked.connect(self.on_activer_saisie)
        self.dlg.pushButton_activer_saisie.setToolTip("Activer la saisie pour l'objet préféré sélectionné")

        # slot pour le bouton "aide"
        self.dlg.pushButton_aide.clicked.connect(self.on_apropos)
        self.dlg.pushButton_aide.setToolTip("A propos de ce plugin")

        # slot de listwidget
        self.dlg.listWidget.itemClicked.connect(self.on_clic_objet_prefere)
        # Connecter le menu contextuel
        self.dlg.listWidget.setContextMenuPolicy(CustomContextMenu)
        self.dlg.listWidget.customContextMenuRequested.connect(self.context_menu)

        self.set_fic_objetpreferes()
        self.init_list_widget()

        self.dlg.show()


