# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ObjetsPref
                                 A QGIS plugin
 Objets préférés
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-11-27
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Gérôme PECHEUR (IGN)
        email                : gerome.pecheur@ign.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os

from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QDialog
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis._core import QgsProject

# Import the code for the dialog
from .objet_prefere_dialog import ObjetsPrefDialog

REP_CONFIG = "CONFIG"
FIC_OBJET_PREFERES = "objets_preferes.txt"

class ObjetsPref:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.dlg = None
        self.iface = iface
        self._fic_objets_pref = None


    def initGui(self):
        pass

    def unload(self):
        pass

    def get_dossier_objets_pref(self) -> str:
        """
            Retourne le chemin du dossier des objets préférés.
            :return: str
            """
        project = QgsProject.instance()
        chemin_projet = project.fileName()
        dossier_projet = os.path.dirname(chemin_projet)
        dossier = os.path.join(dossier_projet, REP_CONFIG)
        return dossier

    def set_fic_objetpreferes(self):
        self._fic_objets_pref = os.path.join(self.get_dossier_objets_pref(), FIC_OBJET_PREFERES)

    def get_fic_objetpreferes(self):
        return self._fic_objets_pref

    def get_objetspreferes(self):
        if self.get_fic_objetpreferes is None:
            self.set_fic_objetpreferes()
        if os.path.exists(self.get_fic_objetpreferes()):
            with open(self.get_fic_objetpreferes(), "r") as f:
                return [line.strip() for line in f.readlines()]
        else:
            print(f"Le fichier {self.get_fic_objetpreferes()} n'existe pas.")
            return []

    def run(self):
        """Run method that performs all the real work"""
        if self.dlg is not None and self.dlg.isVisible():
            return
        self.dlg = ObjetsPrefDialog()
        self.dlg.setParent(self.iface.mainWindow())
        self.dlg.setWindowFlags(Qt.Dialog | Qt.WindowTitleHint | Qt.WindowCloseButtonHint)

        self.set_fic_objetpreferes()

        print(self.get_fic_objetpreferes())


        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # # See if OK was pressed
        if result == QDialog.Rejected:
            pass

